server:
  port: 8443
  ssl:
    enabled: true
    keyAlias: server
    key-password: password
    key-store: classpath:keyStore.jceks
    key-store-password: password
    key-store-type: jceks
    trust-store: classpath:trustStore.jceks
    trust-store-password: password
    trust-store-type: jceks
    clientAuth: NEED
#    protocol: TLS
    enabledProtocols: TLSv1.2,TLSv1.3
    ciphers: TLS_AES_256_GCM_SHA384,ECDHE-RSA-AES256-GCM-SHA384
#  servlet:
#    session:
#      timeout: 15m
logging:
  level:
    org.springframework.security: DEBUG


#spring:
#  autoconfigure:
#    exclude[0]: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
#    exclude[1]: org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration