server:
  port: 8443
  ssl:
    enabled: false
    keyAlias: server
    keyStore: classpath:keyStore.jceks
    keyStorePassword: password
    trustStore: classpath:keyStore.jceks
    trustStorePassword: password
    clientAuth: NEED
#    protocol: TLS
#    enabledProtocols: TLSv1.2
#    ciphers: TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384
  servlet:
    session:
      timeout: 15m
logging:
  level:
    org.springframework.security: DEBUG